/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1b1b20",
        "secondary-container": "#45456d",
        "on-primary": "#00363a",
        "on-secondary-fixed": "#17173d",
        "surface-container-high": "#2a292f",
        "tertiary-fixed": "#ffd7f5",
        "on-secondary-fixed-variant": "#43436b",
        "inverse-surface": "#e4e1e9",
        "on-error": "#690005",
        "on-secondary-container": "#b5b4e3",
        "primary-fixed": "#7df4ff",
        "secondary-fixed": "#e2dfff",
        "error-container": "#93000a",
        "surface-bright": "#39383e",
        "primary": "#dbfcff",
        "on-background": "#e4e1e9",
        "surface": "#131318",
        "secondary-fixed-dim": "#c3c2f2",
        "on-primary-fixed-variant": "#004f54",
        "error": "#ffb4ab",
        "on-primary-fixed": "#002022",
        "surface-container-lowest": "#0e0e13",
        "surface-variant": "#35343a",
        "tertiary": "#fff3f9",
        "on-tertiary-fixed-variant": "#810081",
        "primary-fixed-dim": "#00dbe9",
        "outline-variant": "#3b494b",
        "primary-container": "#00f0ff",
        "on-surface-variant": "#b9cacb",
        "on-primary-container": "#006970",
        "tertiary-fixed-dim": "#ffabf3",
        "outline": "#849495",
        "background": "#131318",
        "on-secondary": "#2c2c53",
        "surface-tint": "#00dbe9",
        "inverse-primary": "#006970",
        "on-surface": "#e4e1e9",
        "surface-container-highest": "#35343a",
        "surface-container": "#1f1f25",
        "secondary": "#c3c2f2",
        "inverse-on-surface": "#303036",
        "tertiary-container": "#ffc9f4",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#380038",
        "surface-dim": "#131318",
        "on-tertiary": "#5b005b",
        "on-tertiary-container": "#a900a9",
        "theme-primary": "rgb(var(--theme-primary) / <alpha-value>)",
        "theme-secondary": "rgb(var(--theme-secondary) / <alpha-value>)",
        "theme-bg": "var(--theme-bg)",
        "cyan": {
          400: "rgb(var(--theme-primary) / <alpha-value>)",
          500: "rgb(var(--theme-primary) / <alpha-value>)",
          900: "rgb(var(--theme-primary) / <alpha-value>)",
          950: "rgb(var(--theme-primary) / <alpha-value>)",
        },
        "magenta": {
          400: "rgb(var(--theme-secondary) / <alpha-value>)",
          500: "rgb(var(--theme-secondary) / <alpha-value>)",
          900: "rgb(var(--theme-secondary) / <alpha-value>)",
        }
      },
      fontFamily: {
        "headline": ['"Space Grotesk"', 'sans-serif'],
        "body": ['"Manrope"', 'sans-serif'],
        "label": ['"Space Grotesk"', 'sans-serif']
      },
      animation: {
        'pulse-slow': 'pulse 8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
